# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dengjen_grpc_pb2 as dengjen__grpc__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dengjen_grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DengjenGrpcStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDengjenVersion = channel.unary_unary(
                '/dengjen_grpc.DengjenGrpc/GetDengjenVersion',
                request_serializer=dengjen__grpc__pb2.Empty.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.Version.FromString,
                _registered_method=True)
        self.LoadVoice = channel.unary_unary(
                '/dengjen_grpc.DengjenGrpc/LoadVoice',
                request_serializer=dengjen__grpc__pb2.VoiceConfigLocation.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.VoiceDescriptor.FromString,
                _registered_method=True)
        self.GetVoiceInfo = channel.unary_unary(
                '/dengjen_grpc.DengjenGrpc/GetVoiceInfo',
                request_serializer=dengjen__grpc__pb2.VoiceRef.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.VoiceDescriptor.FromString,
                _registered_method=True)
        self.GetSynthesisOptions = channel.unary_unary(
                '/dengjen_grpc.DengjenGrpc/GetSynthesisOptions',
                request_serializer=dengjen__grpc__pb2.VoiceRef.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.SynthesisSettings.FromString,
                _registered_method=True)
        self.SetSynthesisOptions = channel.unary_unary(
                '/dengjen_grpc.DengjenGrpc/SetSynthesisOptions',
                request_serializer=dengjen__grpc__pb2.VoiceSynthesisSettings.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.SynthesisSettings.FromString,
                _registered_method=True)
        self.SynthesizeUtterance = channel.unary_stream(
                '/dengjen_grpc.DengjenGrpc/SynthesizeUtterance',
                request_serializer=dengjen__grpc__pb2.SynthesisRequest.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.SynthesisChunk.FromString,
                _registered_method=True)
        self.SynthesizeUtteranceRealtime = channel.unary_stream(
                '/dengjen_grpc.DengjenGrpc/SynthesizeUtteranceRealtime',
                request_serializer=dengjen__grpc__pb2.SynthesisRequest.SerializeToString,
                response_deserializer=dengjen__grpc__pb2.RealtimeAudioChunk.FromString,
                _registered_method=True)


class DengjenGrpcServicer:
    """Missing associated documentation comment in .proto file."""

    def GetDengjenVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadVoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVoiceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSynthesisOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSynthesisOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeUtterance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeUtteranceRealtime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DengjenGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDengjenVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDengjenVersion,
                    request_deserializer=dengjen__grpc__pb2.Empty.FromString,
                    response_serializer=dengjen__grpc__pb2.Version.SerializeToString,
            ),
            'LoadVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadVoice,
                    request_deserializer=dengjen__grpc__pb2.VoiceConfigLocation.FromString,
                    response_serializer=dengjen__grpc__pb2.VoiceDescriptor.SerializeToString,
            ),
            'GetVoiceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVoiceInfo,
                    request_deserializer=dengjen__grpc__pb2.VoiceRef.FromString,
                    response_serializer=dengjen__grpc__pb2.VoiceDescriptor.SerializeToString,
            ),
            'GetSynthesisOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSynthesisOptions,
                    request_deserializer=dengjen__grpc__pb2.VoiceRef.FromString,
                    response_serializer=dengjen__grpc__pb2.SynthesisSettings.SerializeToString,
            ),
            'SetSynthesisOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSynthesisOptions,
                    request_deserializer=dengjen__grpc__pb2.VoiceSynthesisSettings.FromString,
                    response_serializer=dengjen__grpc__pb2.SynthesisSettings.SerializeToString,
            ),
            'SynthesizeUtterance': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeUtterance,
                    request_deserializer=dengjen__grpc__pb2.SynthesisRequest.FromString,
                    response_serializer=dengjen__grpc__pb2.SynthesisChunk.SerializeToString,
            ),
            'SynthesizeUtteranceRealtime': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeUtteranceRealtime,
                    request_deserializer=dengjen__grpc__pb2.SynthesisRequest.FromString,
                    response_serializer=dengjen__grpc__pb2.RealtimeAudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dengjen_grpc.DengjenGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dengjen_grpc.DengjenGrpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DengjenGrpc:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDengjenVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dengjen_grpc.DengjenGrpc/GetDengjenVersion',
            dengjen__grpc__pb2.Empty.SerializeToString,
            dengjen__grpc__pb2.Version.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dengjen_grpc.DengjenGrpc/LoadVoice',
            dengjen__grpc__pb2.VoiceConfigLocation.SerializeToString,
            dengjen__grpc__pb2.VoiceDescriptor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVoiceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dengjen_grpc.DengjenGrpc/GetVoiceInfo',
            dengjen__grpc__pb2.VoiceRef.SerializeToString,
            dengjen__grpc__pb2.VoiceDescriptor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSynthesisOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dengjen_grpc.DengjenGrpc/GetSynthesisOptions',
            dengjen__grpc__pb2.VoiceRef.SerializeToString,
            dengjen__grpc__pb2.SynthesisSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSynthesisOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dengjen_grpc.DengjenGrpc/SetSynthesisOptions',
            dengjen__grpc__pb2.VoiceSynthesisSettings.SerializeToString,
            dengjen__grpc__pb2.SynthesisSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeUtterance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dengjen_grpc.DengjenGrpc/SynthesizeUtterance',
            dengjen__grpc__pb2.SynthesisRequest.SerializeToString,
            dengjen__grpc__pb2.SynthesisChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeUtteranceRealtime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dengjen_grpc.DengjenGrpc/SynthesizeUtteranceRealtime',
            dengjen__grpc__pb2.SynthesisRequest.SerializeToString,
            dengjen__grpc__pb2.RealtimeAudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
